### ISSUE TITLE
Update to latest version of Force CLI

### ISSUE THREAD

**Issue by sumo300** [mwanchap/choco-force-cli#3]
Needs to be updated to latest version of the Force CLI.

**Comment by sumo300** [comment]
I recommend switching this installer to just run the Node.js installer and add a dependency on nodejs.

`npm install sfdx-cli --global`

**Comment by mwanchap** [comment]
Thanks for your patience, I've been a bit slack with checking GitHub notifications! Note that this package is for the "[Force CLI](https://github.com/ForceCLI/force)", an open-source community project, not the official closed-source SFDX CLI which already exists in choco [here](https://community.chocolatey.org/packages/sfdx-cli) (although it appears abandoned).

**Comment by mwanchap** [comment]
Oh, turns out the Force CLI also has a newer version - I've updated this package now. Thanks for reminding me, even though you were referring to a different project 😁
